#remove correlated variables
#user manually selects which layers to remove from rasterstack
#' remove variables
#'
#' A function that removes specified variables from the raster stack of climate variables
#' @param raster_stack A raster stack generated by the get_world_clim function
#' @param variables_to_be_removed A list of variables selected by the user
#' @examples
#' remove_corr_variables(raster_stack, c("bio1", "bio4", "bio10"))
remove_corr_variables <- function(raster_stack, variables_to_be_removed){

  names <- c(names(raster_stack))
  n <- raster::match(variables_to_be_removed, names)

  new <- raster::dropLayer(raster_stack, n)

  return(new)
}
